# Generated by Django 2.2.7 on 2020-01-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseno', models.IntegerField()),
                ('coursename', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('faculty', models.CharField(max_length=100)),
                ('timeduration', models.IntegerField()),
            ],
        ),
    ]
